name = "NASAEarthObservations"
uuid = "9526e54e-4491-4e9f-a840-d78b79cb5e3b"
authors = ["Anshul Singhvi"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
